# -*- coding: utf-8 -*-
"""Survey

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdvdPeD23HfzLErBIPLkCI1DsjegLFke
"""

print("Hi Love <3")
input("Hit enter to continue")
print("You will be asked some very hard questions in a while, this is a very important survey, so be honest All THE BEST")
input("Hit enter to continue")
while True:
  answer = input("""How many times did i say 'I Love You' to you in that auto?
  a) Once
  b) Twice
  c) Three Times
  d) So many times because i love u that much """)

  if answer.lower() == "d":
     print("CORRECT ANSWER WOHOOO")

     break
  else:
     print("HAWW, NO!! ANS AGAIN")

print("Very gooood, ready for next question?")
input("Hit enter to continue")

while True:
  answer = input("""What was the first flower i gave you ?
  a) Rose
  b) Sunflower
  c) Lily
  d) Lotus """)

  if answer.lower() == "d":
     print("CORRECT ANSWER WOHOOO")

     break
  else:
     print("NOOOO, remember again")

print("Wow you are good at this, now next question, readyy?")
input("Hit enter to continue")

while True:
  answer = input("""At which place have we met the most?
  a) CP
  b) Iffco chowk bus stand
  c) Sundar nursery
  d) Deer park """)

  if answer.lower() == "d":
     print("CORRECT ANSWER WOHOOO")
     break
  else:
     print(" Haha, close one.. try again")

print("GREAT, next one's a rhetorical question")
input("Hit enter to continue")

print("Who is the most beautiful girl in the world?..any guesses?")
input("Hit enter to continue")
print("YES YOU GUESSED IT RIGHT..ITS YOUUUUUU")
input("Hit enter to continue")

print("Now the last and most important question...hold your breath...")
input("Hit enter to continue")

attempt = 0

while True:
  answer = input("DO YOU LOVE ME? (i dare you to say no)")
  if answer.lower()== "yes":
    print("I LOVE YOU TOO BABY")
    break

  else:
    attempt += 1
    if attempt == 1:
      print("WRONG haha say no again i dare you")

    elif attempt == 2:
      print("PLSS SAY YESSS PLSSSSSSSSSS")

    else:
      print("I GOT ALL DAY UNTILL YOU SAY YESS")
input("Hit enter to continue")
print("I know we have our ups and downs but i want us to remember our good times more, I love you baby, and i am proud of you <3")
input("Hit enter to continue")
print("Survey finished")