# -*- coding: utf-8 -*-
"""Survey

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdvdPeD23HfzLErBIPLkCI1DsjegLFke
"""

import streamlit as st

st.set_page_config(page_title="Love Survey 💖", page_icon="❤️")

# Session state initialization
if "step" not in st.session_state:
    st.session_state.step = 0

if "attempt" not in st.session_state:
    st.session_state.attempt = 0


def next_step():
    st.session_state.step += 1


st.title("💌 Love Survey 💌")

# STEP 0
if st.session_state.step == 0:
    st.write("Hi Love <3")
    if st.button("Hit enter to continue"):
        next_step()

# STEP 1
elif st.session_state.step == 1:
    st.write(
        "You will be asked some very hard questions in a while, this is a very important survey, so be honest. ALL THE BEST 💖"
    )
    if st.button("Continue"):
        next_step()

# STEP 2 - Question 1
elif st.session_state.step == 2:
    st.subheader("Question 1")
    answer = st.radio(
        "How many times did I say 'I Love You' to you in that auto?",
        ["a", "b", "c", "d"],
        format_func=lambda x: {
            "a": "Once",
            "b": "Twice",
            "c": "Three Times",
            "d": "So many times because I love u that much",
        }[x],
    )

    if st.button("Submit"):
        if answer == "d":
            st.success("CORRECT ANSWER WOHOOO ❤️")
            next_step()
        else:
            st.error("HAWW, NO!! ANS AGAIN")

# STEP 3
elif st.session_state.step == 3:
    st.write("Very gooood, ready for next question?")
    if st.button("Next"):
        next_step()

# STEP 4 - Question 2
elif st.session_state.step == 4:
    st.subheader("Question 2")
    answer = st.radio(
        "What was the first flower I gave you?",
        ["a", "b", "c", "d"],
        format_func=lambda x: {
            "a": "Rose",
            "b": "Sunflower",
            "c": "Lily",
            "d": "Lotus",
        }[x],
    )

    if st.button("Submit"):
        if answer == "d":
            st.success("CORRECT ANSWER WOHOOO 🌸")
            next_step()
        else:
            st.error("NOOOO, remember again")

# STEP 5
elif st.session_state.step == 5:
    st.write("Wow you are good at this, now next question, readyy?")
    if st.button("Next"):
        next_step()

# STEP 6 - Question 3
elif st.session_state.step == 6:
    st.subheader("Question 3")
    answer = st.radio(
        "At which place have we met the most?",
        ["a", "b", "c", "d"],
        format_func=lambda x: {
            "a": "CP",
            "b": "Iffco chowk bus stand",
            "c": "Sundar nursery",
            "d": "Deer park",
        }[x],
    )

    if st.button("Submit"):
        if answer == "d":
            st.success("CORRECT ANSWER WOHOOO 🥰")
            next_step()
        else:
            st.error("Haha, close one.. try again")

# STEP 7
elif st.session_state.step == 7:
    st.write("GREAT, next one's a rhetorical question")
    if st.button("Continue"):
        next_step()

# STEP 8
elif st.session_state.step == 8:
    st.write("Who is the most beautiful girl in the world?..any guesses?")
    if st.button("Reveal Answer"):
        next_step()

# STEP 9
elif st.session_state.step == 9:
    st.success("YES YOU GUESSED IT RIGHT..ITS YOUUUUUU 💖")
    if st.button("Continue"):
        next_step()

# STEP 10
elif st.session_state.step == 10:
    st.write("Now the last and most important question...hold your breath...")
    if st.button("Start Final Question"):
        next_step()

# STEP 11 - Final Question
elif st.session_state.step == 11:
    answer = st.text_input("DO YOU LOVE ME? (i dare you to say no)")

    if st.button("Submit"):
        if answer.lower() == "yes":
            st.success("I LOVE YOU TOO BABY ❤️")
            next_step()

        else:
            st.session_state.attempt += 1

            if st.session_state.attempt == 1:
                st.warning("WRONG haha say no again i dare you")

            elif st.session_state.attempt == 2:
                st.warning("PLSS SAY YESSS PLSSSSSSSSSS")

            else:
                st.warning("I GOT ALL DAY UNTILL YOU SAY YESS")

# STEP 12
elif st.session_state.step == 12:
    st.write(
        "I know we have our ups and downs but I want us to remember our good times more. "
        "I love you baby, and I am proud of you ❤️"
    )

    if st.button("Finish Survey"):
        next_step()

# STEP 13
elif st.session_state.step == 13:
    st.balloons()
    st.success("Survey finished 💖")
